# coding=utf-8
__author__ = 'nsk'
from bs4 import BeautifulSoup

def load_file():
    return open('article/article_1.txt', 'r')

def process(file_input):
    """
    to extract article and some other message about the aritle through html format

    including: title, author, highlight(exclusive in papers from ScienceDirect, might be useful in the future), date,
    abstract, keywords, and full text

    P.S.

    :param file_input: file object generated by load_file module
    :return: dictionary containing what is extracted
    """
    soup = BeautifulSoup(file_input.read(), 'html5lib')
    title_article = soup.title.string.strip()


def write_to_file():
    return

def main():
    process(load_file())

if __name__ == '__main__':
    main()
